

CREATE SCHEMA  COLEGIO;


CREATE TABLE  COLEGIO.IDENTIFICACION (
  idIDENTIFICACION INT NOT NULL,
  NombreIdentificacion VARCHAR(100) NOT NULL,
  PRIMARY KEY (idIDENTIFICACION))



CREATE TABLE COLEGIO.ESTUDIANTE (
  idESTUDIANTE INT NOT NULL AUTO_INCREMENT,
  NombresEs VARCHAR(100) NOT NULL,
  ApellidosEs VARCHAR(100) NOT NULL,
  GeneroEs VARCHAR(45) NOT NULL,
  FechaNacimientoEs DATE NOT NULL,
  DireccionEs VARCHAR(100) NOT NULL,
  TelefonoEs VARCHAR(100) NOT NULL,
  CelularEs VARCHAR(45) NOT NULL,
  CorreoElectronicoEs VARCHAR(45) NULL,
  IDENTIFICACION_idIDENTIFICACION INT NOT NULL,
  PRIMARY KEY (idESTUDIANTE, IDENTIFICACION_idIDENTIFICACION),
  INDEX fk_ESTUDIANTE_IDENTIFICACION_idx (IDENTIFICACION_idIDENTIFICACION ASC) VISIBLE,
  CONSTRAINT fk_ESTUDIANTE_IDENTIFICACION
    FOREIGN KEY (IDENTIFICACION_idIDENTIFICACION)
    REFERENCES COLEGIO.IDENTIFICACION (idIDENTIFICACION)

    )


CREATE TABLE  COLEGIO.PROFESOR (
  idPROFESOR INT NOT NULL AUTO_INCREMENT,
  NombresPr VARCHAR(100) NOT NULL,
  ApellidosPr VARCHAR(100) NOT NULL,
  GeneroPr VARCHAR(45) NOT NULL,
  FechaNacimientoPr VARCHAR(45) NOT NULL,
  TarjetaProfesionalPr VARCHAR(45) NOT NULL,
  TelefonoPr VARCHAR(45) NOT NULL,
  CelularPr VARCHAR(45) NOT NULL,
  CorreoElectronicoPr VARCHAR(45) NOT NULL,
  IDENTIFICACION_idIDENTIFICACION INT NOT NULL,
  PRIMARY KEY (idPROFESOR, IDENTIFICACION_idIDENTIFICACION),
  INDEX fk_PROFESOR_IDENTIFICACION1_idx (IDENTIFICACION_idIDENTIFICACION ASC) VISIBLE,
  CONSTRAINT fk_PROFESOR_IDENTIFICACION1
    FOREIGN KEY (IDENTIFICACION_idIDENTIFICACION)
    REFERENCES COLEGIO.IDENTIFICACION (idIDENTIFICACION)

    )

CREATE TABLE  COLEGIO.CLASE (
  idCLASE INT NOT NULL AUTO_INCREMENT,
  NombreClase VARCHAR(100) NOT NULL,
  PRIMARY KEY (idCLASE))


CREATE TABLE  COLEGIO.ESTUDIANTE_has_CLASE (
  ESTUDIANTE_idESTUDIANTE INT NOT NULL,
  CLASE_idCLASE INT NOT NULL,
  Salon VARCHAR(45) NULL,
  PRIMARY KEY (ESTUDIANTE_idESTUDIANTE, CLASE_idCLASE),
  INDEX fk_ESTUDIANTE_has_CLASE_CLASE1_idx (CLASE_idCLASE ASC) VISIBLE,
  INDEX fk_ESTUDIANTE_has_CLASE_ESTUDIANTE1_idx (ESTUDIANTE_idESTUDIANTE ASC) VISIBLE,
  CONSTRAINT fk_ESTUDIANTE_has_CLASE_ESTUDIANTE1
    FOREIGN KEY (ESTUDIANTE_idESTUDIANTE)
    REFERENCES COLEGIO.ESTUDIANTE (idESTUDIANTE)
	CONSTRAINT fk_ESTUDIANTE_has_CLASE_CLASE1
    FOREIGN KEY (CLASE_idCLASE)
    REFERENCES COLEGIO.CLASE (idCLASE)

    )


CREATE TABLE  COLEGIO.NOTA (
  idNOTA INT NOT NULL AUTO_INCREMENT,
  ESTUDIANTE_has_CLASE_ESTUDIANTE_idESTUDIANTE INT NOT NULL,
  ESTUDIANTE_has_CLASE_CLASE_idCLASE INT NOT NULL,
  NotaFinal DOUBLE NOT NULL,
  PRIMARY KEY (idNOTA, ESTUDIANTE_has_CLASE_ESTUDIANTE_idESTUDIANTE, ESTUDIANTE_has_CLASE_CLASE_idCLASE),
  INDEX fk_NOTA_ESTUDIANTE_has_CLASE1_idx (ESTUDIANTE_has_CLASE_ESTUDIANTE_idESTUDIANTE ASC, ESTUDIANTE_has_CLASE_CLASE_idCLASE ASC) VISIBLE,
  CONSTRAINT fk_NOTA_ESTUDIANTE_has_CLASE1
    FOREIGN KEY (ESTUDIANTE_has_CLASE_ESTUDIANTE_idESTUDIANTE , ESTUDIANTE_has_CLASE_CLASE_idCLASE)
    REFERENCES COLEGIO.ESTUDIANTE_has_CLASE (ESTUDIANTE_idESTUDIANTE , CLASE_idCLASE)

    )



